# Generated by Django 4.1.7 on 2023-03-06 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publication_date', models.DateField()),
                ('lead_paragraph', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='letter',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
