# Generated by Django 4.1.7 on 2023-03-07 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0003_letter_about_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='letter',
            name='votes',
            field=models.BigIntegerField(default=0),
        ),
    ]
