# Generated by Django 4.1.7 on 2023-03-15 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0004_letter_votes'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='web_url',
            field=models.URLField(default='www.nytimes.com'),
        ),
    ]
